src/Entity/Stage.php
<?php

namespace App\Entity;

use App\Repository\StageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StageRepository::class)]
class Stage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $MonthBegin = null;

    #[ORM\Column]
    private ?int $YearBegin = null;

    #[ORM\Column]
    private ?int $MonthEnd = null;

    #[ORM\Column]
    private ?int $YearEnd = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Company = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Descriptif = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMonthBegin(): ?int
    {
        return $this->MonthBegin;
    }

    public function setMonthBegin(int $MonthBegin): self
    {
        $this->MonthBegin = $MonthBegin;

        return $this;
    }

    public function getYearBegin(): ?int
    {
        return $this->YearBegin;
    }

    public function setYearBegin(int $YearBegin): self
    {
        $this->YearBegin = $YearBegin;

        return $this;
    }

    public function getMonthEnd(): ?int
    {
        return $this->MonthEnd;
    }

    public function setMonthEnd(int $MonthEnd): self
    {
        $this->MonthEnd = $MonthEnd;

        return $this;
    }

    public function getYearEnd(): ?int
    {
        return $this->YearEnd;
    }

    public function setYearEnd(int $YearEnd): self
    {
        $this->YearEnd = $YearEnd;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->Company;
    }

    public function setCompany(string $Company): self
    {
        $this->Company = $Company;

        return $this;
    }

    public function getDescriptif(): ?string
    {
        return $this->Descriptif;
    }

    public function setDescriptif(string $Descriptif): self
    {
        $this->Descriptif = $Descriptif;

        return $this;
    }
}

src/Entity/Step.php
<?php

namespace App\Entity;

use App\Repository\StepRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StepRepository::class)]
class Step
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $MonthBegin = null;

    #[ORM\Column]
    private ?int $YearBegin = null;

    #[ORM\Column]
    private ?int $MonthEnd = null;

    #[ORM\Column]
    private ?int $YearEnd = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $skills = null;

    #[ORM\ManyToOne(inversedBy: 'steps')]
    private ?EtapesPro $Etapespro = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMonthBegin(): ?int
    {
        return $this->MonthBegin;
    }

    public function setMonthBegin(int $MonthBegin): self
    {
        $this->MonthBegin = $MonthBegin;

        return $this;
    }

    public function getYearBegin(): ?int
    {
        return $this->YearBegin;
    }

    public function setYearBegin(int $YearBegin): self
    {
        $this->YearBegin = $YearBegin;

        return $this;
    }

    public function getMonthEnd(): ?int
    {
        return $this->MonthEnd;
    }

    public function setMonthEnd(int $MonthEnd): self
    {
        $this->MonthEnd = $MonthEnd;

        return $this;
    }

    public function getYearEnd(): ?int
    {
        return $this->YearEnd;
    }

    public function setYearEnd(int $YearEnd): self
    {
        $this->YearEnd = $YearEnd;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSkills(): ?string
    {
        return $this->skills;
    }

    public function setSkills(string $skills): self
    {
        $this->skills = $skills;

        return $this;
    }

    public function getEtapespro(): ?EtapesPro
    {
        return $this->Etapespro;
    }

    public function setEtapespro(?EtapesPro $Etapespro): self
    {
        $this->Etapespro = $Etapespro;

        return $this;
    }
}

src/Form/StepType.php
<?php

namespace App\Form;

use App\Entity\Step;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StepType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('monthbegin')
            ->add('yearbegin')
            ->add('monthend')
            ->add('yearend')
            ->add('description')
            ->add('skills')
            ->add('Etapespro', null, ['choice_label' => 'company'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Step::class,
        ]);
    }
}

src/Controller/StepController.php
<?php

namespace App\Controller;

use App\Entity\Step;
use App\Form\StepType;
use App\Repository\StepRepository;
use App\Repository\EtapesProRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/step')]
class StepController extends AbstractController
{
    #[Route('/', name: 'app_step_index', methods: ['GET'])]
    public function index(StepRepository $stepRepository, EtapesProRepository $etapesProRepository): Response
    {
        return $this->render('step/index.html.twig', [
            'steps' => $stepRepository->findAll(),
            ]);
    }

    #[Route('/new', name: 'app_step_new', methods: ['GET', 'POST'])]
    public function new(Request $request, StepRepository $stepRepository): Response
    {
        $step = new Step();
        $form = $this->createForm(StepType::class, $step);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $stepRepository->save($step, true);

            return $this->redirectToRoute('app_step_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('step/new.html.twig', [
            'step' => $step,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_step_show', methods: ['GET'])]
    public function show(Step $step): Response
    {
        return $this->render('step/show.html.twig', [
            'step' => $step,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_step_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Step $step, StepRepository $stepRepository): Response
    {
        $form = $this->createForm(StepType::class, $step);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $stepRepository->save($step, true);

            return $this->redirectToRoute('app_step_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('step/edit.html.twig', [
            'step' => $step,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_step_delete', methods: ['POST'])]
    public function delete(Request $request, Step $step, StepRepository $stepRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$step->getId(), $request->request->get('_token'))) {
            $stepRepository->remove($step, true);
        }

        return $this->redirectToRoute('app_step_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/step/_delete_form.html.twig
<form method="post" action="{{ path('app_step_delete', {'id': step.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ step.id) }}">
    <button class="btn">Delete</button>
</form>

templates/step/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Step{% endblock %}

{% block body %}
    <h1>Edit Step</h1>

    {{ include('step/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_step_index') }}">back to list</a>

    {{ include('step/_delete_form.html.twig') }}
{% endblock %}

templates/step/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Step index{% endblock %}

{% block body %}
    <h1>Step index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Month_begin</th>
                <th>Year_begin</th>
                <th>Month_end</th>
                <th>Year_end</th>
                <th>Description</th>
                <th>Skills</th>
                <th>Entreprise</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for step in steps %}
            <tr>
                <td>{{ step.id }}</td>
                <td>{{ step.MonthBegin }}</td>
                <td>{{ step.YearBegin }}</td>
                <td>{{ step.monthEnd }}</td>
                <td>{{ step.yearEnd }}</td>
                <td>{{ step.description }}</td>
                <td>{{ step.skills }}</td>
                <td>{{ step.etapespro.company }}</td>
                <td>
                    <a href="{{ path('app_step_show', {'id': step.id}) }}">show</a>
                    <a href="{{ path('app_step_edit', {'id': step.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_step_new') }}">Create new</a>
{% endblock %}

templates/step/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Step{% endblock %}

{% block body %}
    <h1>Create new Step</h1>

    {{ include('step/_form.html.twig') }}

    <a href="{{ path('app_step_index') }}">back to list</a>
{% endblock %}

templates/step/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Step{% endblock %}

{% block body %}
    <h1>Step</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ step.id }}</td>
            </tr>
            <tr>
                <th>Month_begin</th>
                <td>{{ step.MonthBegin }}</td>
            </tr>
            <tr>
                <th>Year_begin</th>
                <td>{{ step.YearBegin }}</td>
            </tr>
            <tr>
                <th>Month_end</th>
                <td>{{ step.monthEnd }}</td>
            </tr>
            <tr>
                <th>Year_end</th>
                <td>{{ step.yearEnd }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ step.description }}</td>
            </tr>
            <tr>
                <th>Skills</th>
                <td>{{ step.skills }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_step_index') }}">back to list</a>

    <a href="{{ path('app_step_edit', {'id': step.id}) }}">edit</a>

    {{ include('step/_delete_form.html.twig') }}
{% endblock %}