src/Entity/EtapesPro.php
<?php

namespace App\Entity;

use App\Repository\EtapesProRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EtapesProRepository::class)]
class EtapesPro
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 10)]
    private ?string $Mois = null;

    #[ORM\Column]
    private ?int $Year = null;

    #[ORM\Column(length: 255)]
    private ?string $Job = null;

    #[ORM\Column(length: 255)]
    private ?string $Company = null;

    #[ORM\OneToMany(mappedBy: 'Etapespro', targetEntity: Step::class)]
    private Collection $steps;

    public function __construct()
    {
        $this->steps = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMois(): ?string
    {
        return $this->Mois;
    }

    public function setMois(string $Mois): self
    {
        $this->Mois = $Mois;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->Year;
    }

    public function setYear(int $Year): self
    {
        $this->Year = $Year;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->Job;
    }

    public function setJob(string $Job): self
    {
        $this->Job = $Job;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->Company;
    }

    public function setCompany(string $Company): self
    {
        $this->Company = $Company;

        return $this;
    }

    /**
     * @return Collection<int, Step>
     */
    public function getSteps(): Collection
    {
        return $this->steps;
    }

    public function addStep(Step $step): self
    {
        if (!$this->steps->contains($step)) {
            $this->steps->add($step);
            $step->setEtapespro($this);
        }

        return $this;
    }

    public function removeStep(Step $step): self
    {
        if ($this->steps->removeElement($step)) {
            // set the owning side to null (unless already changed)
            if ($step->getEtapespro() === $this) {
                $step->setEtapespro(null);
            }
        }

        return $this;
    }
}

src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $Date = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Texte = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?int
    {
        return $this->Date;
    }

    public function setDate(int $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->Texte;
    }

    public function setTexte(string $Texte): self
    {
        $this->Texte = $Texte;

        return $this;
    }
}

src/Entity/Stage.php
<?php

namespace App\Entity;

use App\Repository\StageRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StageRepository::class)]
class Stage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $MonthBegin = null;

    #[ORM\Column]
    private ?int $YearBegin = null;

    #[ORM\Column]
    private ?int $MonthEnd = null;

    #[ORM\Column]
    private ?int $YearEnd = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Company = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Descriptif = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMonthBegin(): ?int
    {
        return $this->MonthBegin;
    }

    public function setMonthBegin(int $MonthBegin): self
    {
        $this->MonthBegin = $MonthBegin;

        return $this;
    }

    public function getYearBegin(): ?int
    {
        return $this->YearBegin;
    }

    public function setYearBegin(int $YearBegin): self
    {
        $this->YearBegin = $YearBegin;

        return $this;
    }

    public function getMonthEnd(): ?int
    {
        return $this->MonthEnd;
    }

    public function setMonthEnd(int $MonthEnd): self
    {
        $this->MonthEnd = $MonthEnd;

        return $this;
    }

    public function getYearEnd(): ?int
    {
        return $this->YearEnd;
    }

    public function setYearEnd(int $YearEnd): self
    {
        $this->YearEnd = $YearEnd;

        return $this;
    }

    public function getCompany(): ?string
    {
        return $this->Company;
    }

    public function setCompany(string $Company): self
    {
        $this->Company = $Company;

        return $this;
    }

    public function getDescriptif(): ?string
    {
        return $this->Descriptif;
    }

    public function setDescriptif(string $Descriptif): self
    {
        $this->Descriptif = $Descriptif;

        return $this;
    }
}

src/Controller/Mainpage.php
<?php

namespace App\Controller;

use App\Entity\EtapesPro;
use App\Repository\EtapesProRepository;
use App\Repository\FormationRepository;
use App\Repository\SkillsRepository;
use App\Repository\StageRepository;
use App\Repository\StepRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\QueryBuilder;


class Mainpage extends AbstractController

{
    #[Route('/main', name: 'main')]
    public function index(EtapesProRepository $etapesProRepository, FormationRepository $formationRepository,SkillsRepository $skillsRepository,StageRepository $stagesRepository,StepRepository $stepsRepository): Response

    {
        $EtapesPro=$etapesProRepository->findBy([], ['Year' => 'DESC']);
        $Formations=$formationRepository->findBy([], ['Date' => 'DESC']);
        $Skills=$skillsRepository->findAll();
        $Stages=$stagesRepository->findBy([], ['YearBegin' => 'DESC']);
        $Steps=$stepsRepository->findBy([], ['YearBegin' => 'DESC']);

        return $this->render('mainpage/main.html.twig', [

            'etapespro' => $EtapesPro,
            'formations' => $Formations,
            'skills' => $Skills,
            'stages' => $Stages,
            'steps' => $Steps,

        ]);
    }
}

templates/mainpage/main.html.twig
{% extends 'base.html.twig' %}

{% block title %}All programs{% endblock %}


{% block body %}


<script>
    function cb(response) {
        document.getElementById('visits').innerText = response.value;
    }
</script>
<script async src="https://api.countapi.xyz/hit/cvjulienbonzom.online/visits?callback=cb"></script>
        <div class="bloc_page">
            <div class="bordure"><!-- Bordure esthetique --></div>
            <bodyLast>
                <div class="texte">
                    <div class="partie_inf">

                        <header>

                            <div class="entete_sup3">
                                <div class="entete_sup2">
                                    <div class="entete">
                                        <div class="nom">Julien BONZOM</div>
                                        <div class="texte2">
                                            100, avenue de la libération
                                            <br /> 33700 MERIGNAC
                                            <br /> tel: 06.76.11.84.57</div>

                                        <div class="mail"><a href="mailto:bonzomj@gmail.com">bonzomj@gmail.com</a></div>
                                        <br />
                                        <i>This site has been visited <span id="visits"></span> times.</i>
                                    </div>


                                    <div class="fonction">Développeur/Ingénieur Mécanique</div><!-- Titre -->
                                </div>
                                <div class="separation"></div>
                            </div>

                            <a href={{ asset("photo_J_BONZOM_2.jpg") }} ><img src={{ asset("photo_J_BONZOM_mini2.jpg") }}  alt="Photo de Julien BONZOM" title="Cliquez pour agrandir" class="fin"/></a><!--Image photo pouvant etre agrandie-->

                        </header>


                        <div class="total">
                            <section> <!-- Section -->
                                <div class="base">
                                    <div class="competences"><p><h2>Compétences:</h2>
                                        <ul>
                                            {% for skill in skills %}
                                            <li><Strong>Languages Informatiques:</Strong> {{ skill.Languages }}</li>
                                            <li><Strong>Outils AIRBUS:</Strong> {{ skill.AIRBUS }}</li>
                                            <li><Strong>Outils DASSAULT:</Strong> {{ skill.DASSAULT }}</li>
                                            <li><Strong>Outils CALCUL/DESIGN:</Strong> {{ skill.CALCUL_DESIGN }}</li>
                                            <li><Strong>Outils OFFICE:</Strong> {{ skill.OFFICE }}</li>
                                            <li><Strong>Langues:</Strong> {{ skill.Langues }}</li>
                                            {% endfor %}
                                        </ul>

                                    </div>

                                    <div class="formation"><p><h2>Formation:</h2>
                                        {% for formation in formations %}
                                        <ul>
                                            <li><Strong>{{ formation.date }}</Strong> {{ formation.texte }}</li>
                                        </ul>
                                        {% endfor %}

                                    </div>

                                    <div class="stages"><p><h2>Stages:</h2>
                                        <ul>
                                        {% for stage in stages %}
                                        <li><Strong>{{ stage.monthbegin }}/{{ stage.yearbegin }} – {{ stage.monthend }}/{{ stage.yearend }}:</Strong><br />Stage chez {{ stage.company }}.<br />{{ stage.descriptif }}</li>
                                        {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="loisirs"><p><h2>Loisirs:</h2>
                                        <ul>
                                            <li><i><a href="/loisirs#titres_montagne" >Sports de montagne</a>, sports de mer, <a href="/loisirs#titres_musique" >ateliers de musique Jazz</a>.</i></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="espace"></div><!-- espace -->
                                <div class="pro"><h2>Expériences Professionnelles:</h2>
                                    <a href="http://127.0.0.1:8000/CV-J_BONZOM.pdf" target="_blank"><i><Strong>Curriculum vitae</Strong></i></a><br>
                                    {% set iteration = 0 %}
                                    {% for etapepro in etapespro %}
                                    {% set iteration = iteration + 1 %}
                                    <h3><Strong>{{ etapepro.mois }} {{ etapepro.year }} - {{ etapepro.job }} chez {{ etapepro.company }}</Strong><br /></h3>

                                        <img src={{ asset("menu.jpg") }} title="Cliquez pour etendre" id={{ 'bouton'~ iteration }} width="50" style="text-align: center"/>

                                        <div id={{ 'cacher'~ iteration }}>
                                        <ul>
                                            {% for step in steps %}
                                                {% if  step.etapespro.company  ==  etapepro.company  %}
                                                <li><Strong>{{ step.monthbegin }}/{{ step.yearbegin }} – {{ step.monthend }}/{{ step.yearend }}:</Strong><br />{{ step.description }}<br/>
                                                    <i>Utilisation {{ step.skills }}</i>
                                                </li>
                                                {% endif %}
                                            {% endfor %}
                                        </ul>
                                        </div>
                                    <br>
                                    {% endfor %}




            </div>
<script>
    let bouton1 = document.getElementById("bouton1");
    let bouton2 = document.getElementById("bouton2");
    let bouton3 = document.getElementById("bouton3");
    let bouton4 = document.getElementById("bouton4");
    let bouton5 = document.getElementById("bouton5");
    let bouton6 = document.getElementById("bouton6");

    let cacher1 = document.getElementById("cacher1");
    let cacher2 = document.getElementById("cacher2");
    let cacher3 = document.getElementById("cacher3");
    let cacher4 = document.getElementById("cacher4");
    let cacher5 = document.getElementById("cacher5");
    let cacher6 = document.getElementById("cacher6");



            bouton1.addEventListener('click', function () {
                if (cacher1.style.display === "none") {
                    cacher1.style.display = "block";
                    bouton1.src = "menu2.jpg";
                    bouton1.title = "Cliquez pour réduire";
                } else {
                    cacher1.style.display = "none";
                    bouton1.src = "menu.jpg";
                    bouton1.title = "Cliquez pour étendre";

                }
            }
        )


            bouton2.addEventListener('click', function () {
                    if (cacher2.style.display === "none") {
                        cacher2.style.display = "block";
                        bouton2.src = "menu2.jpg";
                        bouton2.title = "Cliquez pour réduire";
                    } else {
                        cacher2.style.display = "none";
                        bouton2.src = "menu.jpg";
                        bouton2.title = "Cliquez pour étendre";

                    }
                }
            )

            bouton3.addEventListener('click', function () {
                    if (cacher3.style.display === "none") {
                        cacher3.style.display = "block";
                        bouton3.src = "menu2.jpg";
                        bouton3.title = "Cliquez pour réduire";
                    } else {
                        cacher3.style.display = "none";
                        bouton3.src = "menu.jpg";
                        bouton3.title = "Cliquez pour étendre";

                    }
                }
            )

    bouton4.addEventListener('click', function () {
            if (cacher4.style.display === "none") {
                cacher4.style.display = "block";
                bouton4.src = "menu2.jpg";
                bouton4.title = "Cliquez pour réduire";
            } else {
                cacher4.style.display = "none";
                bouton4.src = "menu.jpg";
                bouton4.title = "Cliquez pour étendre";

            }
        }
    )

    bouton5.addEventListener('click', function () {
            if (cacher5.style.display === "none") {
                cacher5.style.display = "block";
                bouton5.src = "menu2.jpg";
                bouton5.title = "Cliquez pour réduire";
            } else {
                cacher5.style.display = "none";
                bouton5.src = "menu.jpg";
                bouton5.title = "Cliquez pour étendre";

            }
        }
    )

    bouton5.addEventListener('click', function () {
            if (cacher6.style.display === "none") {
                cacher6.style.display = "block";
                bouton6.src = "menu2.jpg";
                bouton6.title = "Cliquez pour réduire";
            } else {
                cacher6.style.display = "none";
                bouton6.src = "menu.jpg";
                bouton6.title = "Cliquez pour étendre";

            }
        }
    )
    function AdapterDivAResolution() {
        let x_res = screen.width;
        let y_res = screen.height;
        const bouton1 = document.getElementById("bouton1")
        if(x_res < 1024)
        {
            bouton1.src="./images/menu2.jpg";
            bouton1.style.display = "block";
            bouton1.style.visibility="visible";
        }
    }
    AdapterDivAResolution()
    bouton1.addEventListener('click',cliquage, false);
</script>
   {% endblock %}